# Copyright 2023 The Unitary Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import cirq

a0 = cirq.NamedQubit('a0')
a1 = cirq.NamedQubit('a1')
a2 = cirq.NamedQubit('a2')
a3 = cirq.NamedQubit('a3')
a4 = cirq.NamedQubit('a4')
a5 = cirq.NamedQubit('a5')
a6 = cirq.NamedQubit('a6')
a7 = cirq.NamedQubit('a7')
a8 = cirq.NamedQubit('a8')
a9 = cirq.NamedQubit('a9')
b0 = cirq.NamedQubit('b0')
b1 = cirq.NamedQubit('b1')
b2 = cirq.NamedQubit('b2')
b3 = cirq.NamedQubit('b3')
b4 = cirq.NamedQubit('b4')
b5 = cirq.NamedQubit('b5')
b6 = cirq.NamedQubit('b6')
b7 = cirq.NamedQubit('b7')
b8 = cirq.NamedQubit('b8')
b9 = cirq.NamedQubit('b9')
c0 = cirq.NamedQubit('c0')
c1 = cirq.NamedQubit('c1')
c2 = cirq.NamedQubit('c2')
c3 = cirq.NamedQubit('c3')
c4 = cirq.NamedQubit('c4')
c5 = cirq.NamedQubit('c5')
c6 = cirq.NamedQubit('c6')
c7 = cirq.NamedQubit('c7')
c8 = cirq.NamedQubit('c8')
c9 = cirq.NamedQubit('c9')
d0 = cirq.NamedQubit('d0')
d1 = cirq.NamedQubit('d1')
d2 = cirq.NamedQubit('d2')
d3 = cirq.NamedQubit('d3')
d4 = cirq.NamedQubit('d4')
d5 = cirq.NamedQubit('d5')
d6 = cirq.NamedQubit('d6')
d7 = cirq.NamedQubit('d7')
d8 = cirq.NamedQubit('d8')
d9 = cirq.NamedQubit('d9')
e0 = cirq.NamedQubit('e0')
e1 = cirq.NamedQubit('e1')
e2 = cirq.NamedQubit('e2')
e3 = cirq.NamedQubit('e3')
e4 = cirq.NamedQubit('e4')
e5 = cirq.NamedQubit('e5')
e6 = cirq.NamedQubit('e6')
e7 = cirq.NamedQubit('e7')
e8 = cirq.NamedQubit('e8')
e9 = cirq.NamedQubit('e9')
f0 = cirq.NamedQubit('f0')
f1 = cirq.NamedQubit('f1')
f2 = cirq.NamedQubit('f2')
f3 = cirq.NamedQubit('f3')
f4 = cirq.NamedQubit('f4')
f5 = cirq.NamedQubit('f5')
f6 = cirq.NamedQubit('f6')
f7 = cirq.NamedQubit('f7')
f8 = cirq.NamedQubit('f8')
f9 = cirq.NamedQubit('f9')
g0 = cirq.NamedQubit('g0')
g1 = cirq.NamedQubit('g1')
g2 = cirq.NamedQubit('g2')
g3 = cirq.NamedQubit('g3')
g4 = cirq.NamedQubit('g4')
g5 = cirq.NamedQubit('g5')
g6 = cirq.NamedQubit('g6')
g7 = cirq.NamedQubit('g7')
g8 = cirq.NamedQubit('g8')
g9 = cirq.NamedQubit('g9')
h0 = cirq.NamedQubit('h0')
h1 = cirq.NamedQubit('h1')
h2 = cirq.NamedQubit('h2')
h3 = cirq.NamedQubit('h3')
h4 = cirq.NamedQubit('h4')
h5 = cirq.NamedQubit('h5')
h6 = cirq.NamedQubit('h6')
h7 = cirq.NamedQubit('h7')
h8 = cirq.NamedQubit('h8')
h9 = cirq.NamedQubit('h9')
i0 = cirq.NamedQubit('i0')
i1 = cirq.NamedQubit('i1')
i2 = cirq.NamedQubit('i2')
i3 = cirq.NamedQubit('i3')
i4 = cirq.NamedQubit('i4')
i5 = cirq.NamedQubit('i5')
i6 = cirq.NamedQubit('i6')
i7 = cirq.NamedQubit('i7')
i8 = cirq.NamedQubit('i8')
i9 = cirq.NamedQubit('i9')
