name: Python formatting

on: [push, pull_request]

# Declare default permissions as read only.
permissions: read-all

jobs:
  lint:
    name: Run black
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
      - name: Set up problem matcher for Black output
        run: echo '::add-matcher::.github/problem-matchers/black.json'
      - uses: psf/black@af0ba72a73598c76189d6dd1b21d8532255d5942 # stable
        with:
          src: "./unitary"
