name: Type Check

on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install mypy
        run: |
          python -m pip install --upgrade pip
          pip install mypy
      - name: Type check
        run: dev_tools/mypy || true
